[package]
name = "polars_ext"
version = "0.6.2"
authors = ["Giorgi Vladimirovich Kazakov", "Roman Alexandrovich Sidorov"]
edition = "2024"

[dependencies]
ahash = "0.8.12"
polars = { git = "https://github.com/pola-rs/polars", rev = "bf6a425", default-features = false, features = [
    "abs",
    "dtype-struct",
    "fmt_no_tty",
    "lazy",
    "round_series",
    # "row_hash",
] }
polars-arrow = { git = "https://github.com/pola-rs/polars", rev = "bf6a425", optional = true }
polars-utils = { version = "0.53.0", features = ["nightly"] }
typed-builder = "0.23.2"

const_format = { version = "0.2.36", optional = true }

[features]
default = ["array"]

array = [
    "const_format",
    "polars/array_arithmetic",
    "polars/array_to_struct",
    "polars/dtype-array",
    "polars/dtype-struct",
    #
    "polars/dtype-datetime",
    "polars/meta",
    "polars/strings",
]
precision = ["polars/dtype-decimal"]
temporal_conversions = ["dep:polars-arrow"]
