[package]
name = "polars_ext"
version = "0.6.2"
authors = ["Giorgi Vladimirovich Kazakov", "Roman Alexandrovich Sidorov"]
edition = "2024"

[dependencies]
ahash = "0.8.12"
polars = { version = "0.52.0", default-features = false, features = [
    "abs",
    "dtype-struct",
    "fmt_no_tty",
    "lazy",
    "round_series",
    # "row_hash",
] }
polars-arrow = { version = "0.52.0", optional = true }
polars-utils = "0.52.0"
typed-builder = "0.23.2"

const_format = { version = "0.2.36", optional = true }

[features]
default = ["array"]

array = [
    "const_format",
    "polars/array_arithmetic",
    "polars/array_to_struct",
    "polars/dtype-array",
    "polars/dtype-struct",
    #
    "polars/dtype-datetime",
    "polars/meta",
    "polars/strings",
]
precision = ["polars/dtype-decimal"]
temporal_conversions = ["dep:polars-arrow"]
