[package]
name = "polars_ext"
version = "0.6.0"
authors = ["Giorgi Vladimirovich Kazakov", "Roman Alexandrovich Sidorov"]
edition = "2024"

[dependencies]
ahash = "0.8.12"
polars = { git = "https://github.com/pola-rs/polars", rev = "099564e", default-features = false, features = [
    "abs",
    "dtype-struct",
    "fmt_no_tty",
    "lazy",
    "round_series",
    # "row_hash",
] }
polars-arrow = { git = "https://github.com/pola-rs/polars", rev = "099564e", optional = true }

[features]
default = []

array = ["polars/array_to_struct", "polars/dtype-struct"]
precision = ["polars/dtype-decimal"]
temporal_conversions = ["dep:polars-arrow"]
