[package]
name = "polars_ext"
version = "0.1.2"
edition = "2024"

[dependencies]
ahash = "0.8.11"
polars = { version = "0.46.0", default-features = false, features = [
    "dtype-struct",
    "fmt_no_tty",
    "lazy",
    "round_series",
] }
